# -*- coding: utf-8 -*-
"""sentiment

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dzy3IgoEi933meP5-rGG0QR-vTwYFhEk
"""

###################################
# Sentiment Assessment System#
###################################

# Pacote de Implementação da Máquina Preditiva
import streamlit as st
# Pacote de PLN - NLTK - Natural Language Tool Kit
import nltk

# Titulo do sistema
st.write("# Sentiment Assessment System")

# Entrada de dados - A manifestação do Cliente
user_input = st.text_input("Please rate our service:   :  ")

# Criação da Máquina Preditiva de Satisfação do Cliente
from nltk.sentiment.vader import SentimentIntensityAnalyzer

nltk.download("vader_lexicon")
s = SentimentIntensityAnalyzer()
score = s.polarity_scores(user_input)

# Refinamento

if score == 0:
    st.write("### On the middle ")

elif score["neg"] != 0:
  st.write("### Negative Assessment")

elif score["pos"] != 0:
  st.write("### Positive Assessment")